# action.yml
name: 'Upload mender artifact'
description: 'Upload a mender artifact to a hosted Mender backend instance'
inputs:
  mender_user:
    description: 'username for the hosted Mender backend account to be used'
    required: true
  mender_password:
    description: 'password for the hosted Mender backend account to be used'
    required: true
  mender_uri:
    description: 'URI for the hosted Mender backend account to be used'
    required: false
    default: 'https://hosted.mender.io'
  mender_artifact:
    description: 'path of the artifact to be uploaded, relative to GITHUB_WORKSPACE'
    required: true
runs:
  using: "composite"
  steps:
    - id: get_access_token
      run: |
        MENDER_TOKEN=$(curl -s -X POST -u ${{ inputs.mender_user }}:"${{ inputs.mender_password }}a" ${{ inputs.mender_uri }}/api/management/v1/useradm/auth/login); \
        echo "curl result 1: $?"; \
        if [ "$?" -ne "0" ]; then echo eek1; exit $?; fi && \
        echo "::set-output name=MENDER_TOKEN::${MENDER_TOKEN}"
      shell: bash
    - id: upload_artifact
      run: |
        curl -s -X POST ${{ inputs.mender_uri }}/api/management/v1/deployments/artifacts \
        -H 'Content-Type: multipart/form-data' \
        -H 'Accept: application/json' \
        -H "Authorization: Bearer ${{ steps.get_access_token.outputs.MENDER_TOKEN }}" \
        -F artifact=@${GITHUB_WORKSPACE}/${{ inputs.mender_artifact }}; \
        echo "curl result 1: $?"; \
        if [ "$?" -ne "0" ]; then echo eek2; exit $?; fi
      shell: bash
